name: Node CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm test
          npm run test:bundle
      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run serve
          wait-on: "http://localhost:8080"
          wait-on-timeout: 60
